set(CMAKE_SYSTEM_NAME               Generic)
set(CMAKE_SYSTEM_PROCESSOR          arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE   STATIC_LIBRARY)

set(CMAKE_C_COMPILER_ID GNU)
set(CMAKE_CXX_COMPILER_ID GNU)

set(TOOLCHAIN_PREFIX arm-none-eabi-)

# Toolchain location, in order of preference:
#   1. $STM32_CUBECLT_PATH (root of an STM32CubeCLT install)
#   2. newest STM32CubeCLT found in /opt/st/ (its default install location)
#   3. arm-none-eabi-gcc on PATH
if(DEFINED ENV{STM32_CUBECLT_PATH})
    set(STM32_TOOLCHAIN_PATH "$ENV{STM32_CUBECLT_PATH}/GNU-tools-for-STM32/bin")
else()
    file(GLOB _cubeclt_candidates "/opt/st/stm32cubeclt_*")
    list(SORT _cubeclt_candidates)
    if(_cubeclt_candidates)
        list(POP_BACK _cubeclt_candidates _cubeclt_root)
        set(STM32_TOOLCHAIN_PATH "${_cubeclt_root}/GNU-tools-for-STM32/bin")
    else()
        set(STM32_TOOLCHAIN_PATH "")
    endif()
endif()
if(STM32_TOOLCHAIN_PATH AND EXISTS "${STM32_TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}gcc")
    set(TOOLCHAIN_BIN "${STM32_TOOLCHAIN_PATH}/")
else()
    set(TOOLCHAIN_BIN "")
endif()

set(CMAKE_C_COMPILER   ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}g++)
set(CMAKE_LINKER       ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}g++)
set(CMAKE_OBJCOPY      ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE         ${TOOLCHAIN_BIN}${TOOLCHAIN_PREFIX}size)

set(CMAKE_EXECUTABLE_SUFFIX_ASM ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C   ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".elf")
